apiVersion: v1
kind: ReplicationController
metadata:
  name: ${JENKINS_NAME}
  labels:
    name: ${JENKINS_NAME}
spec:
  replicas: 1
  selector:
    name: ${JENKINS_NAME}
  template:
    metadata:
      labels:
        name: ${JENKINS_NAME}
    spec:
      containers:
      - env:
        - name: plugins
          value: "${plugins}"
        name: jenkins-primary
        image: jenkins:1.642.2
        ports:
        - containerPort: 8080
      - name: jenkins-plugins
        image: rancher/jenkins-plugins:v0.1.1
      - name: jenkins-datavolume
        image: busybox
        volumeMounts:
        - name: jenkins-workspace
          mountPath: /var/jenkins_home/
      volumes:
      - name: jenkins-workspace
        emptyDir: {}