apiVersion: v1
kind: ReplicationController
metadata:
  name: ${JENKINS_NAME}
  labels:
    name: ${JENKINS_NAME}
  namespace: default
spec:
  replicas: 1
  selector:
    name: ${JENKINS_NAME}
  template:
    metadata:
      labels:
        name: ${JENKINS_NAME}
    spec:
      containers:
      - env:
        - name: PLUGINS
          value: "${plugins}"
        name: jenkins-primary
        image: jenkins:1.642.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /var/jenkins_home/
          name: jenkins-workspace

      - name: jenkins-plugins
        image: rancher/jenkins-plugins:v0.1.1
        imagePullPolicy: Always
      volumes:
      - name: jenkins-workspace
        emptyDir: {}
