apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
      - name: jenkins-primary
        image: jenkins:1.642.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /var/jenkins_home/
          name: jenkins-workspace
      - name: jenkins-plugins
        image: rancher/jenkins-plugins:v0.1.1
        imagePullPolicy: Always
        env:
        - name: PLUGINS
          value: "${PLUGINS}"
      volumes:
      - name: jenkins-workspace
        emptyDir: {}