apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  labels:
    name: ${SERVICE_NAME}
  namespace: pratik
spec:
  type: NodePort
  ports:
  - port: ${PORT}
  selector:
    name: ${JENKINS_NAME}